#配置公告路径
server:
   servlet:
     context-path: /springboot
   port: 8081
   max-http-header-size: 102400
spring:
  #配置接口超时时间
  mvc:
    async:
      request-timeout: 50000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  jta:
#      atomikos:
#        properties:
#          max-actives: 50
#          max-timeout: 300000
#          default-jta-timeout: 10000
#          enable-logging: true
  #  配置数据源
  ds1:
      datasource:
        xa:
          data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/amlbst_fat?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: amlbst
          password: 123456
      mybatis:
         mapper-locations: classpath:mapping/ds1/*.xml
         config-location: classpath:mybatis-config.xml

  ds2:
      datasource:
        xa:
          data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/amlbht_fat?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: amlbht
          password: 123456
      mybatis:
         mapper-locations: classpath:mapping/ds1/*.xml
         config-location: classpath:mybatis-config.xml
druid:
  filters: stat, wall
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 10
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: false

