server:
   port: 8081

spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: amlbst
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/amlbst_fat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource

    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: amlbht
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/amlbht_fat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
